language: node_js
node_js:
  - "6"
  - "7"
  - "8"
install:
  - npm install -g codecov nyc
script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov --token=08ad1224-eea1-44cd-9f3d-646ef576ae9e