language: node_js
node_js:
  - "6"
  - "7"
  - "8"
cache:
  directories:
  - node_modules
script:
  - nyc --reporter=lcov --reporter=text-lcov yarn test # Include coverage when running tests
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=QNrphZfhlmbaEPclCL5dbnEkEMCCV01BB npm run coveralls